module BRU(
  input         io_valid, // @[src/main/scala/backend/execute/BRU.scala 17:14]
  input  [31:0] io_uop_pc, // @[src/main/scala/backend/execute/BRU.scala 17:14]
  input  [3:0]  io_uop_ctrl_bruOp, // @[src/main/scala/backend/execute/BRU.scala 17:14]
  input  [6:0]  io_uop_robIdxFull, // @[src/main/scala/backend/execute/BRU.scala 17:14]
  input  [31:0] io_rs1, // @[src/main/scala/backend/execute/BRU.scala 17:14]
  input  [31:0] io_rs2, // @[src/main/scala/backend/execute/BRU.scala 17:14]
  output [31:0] io_result, // @[src/main/scala/backend/execute/BRU.scala 17:14]
  output        io_redirect_valid, // @[src/main/scala/backend/execute/BRU.scala 17:14]
  output [5:0]  io_redirect_bits_robIdx, // @[src/main/scala/backend/execute/BRU.scala 17:14]
  output        io_isBranch // @[src/main/scala/backend/execute/BRU.scala 17:14]
);
  wire  eq = io_rs1 == io_rs2; // @[src/main/scala/backend/execute/BRU.scala 34:18]
  wire  ne = ~eq; // @[src/main/scala/backend/execute/BRU.scala 35:13]
  wire  lt = $signed(io_rs1) < $signed(io_rs2); // @[src/main/scala/backend/execute/BRU.scala 36:25]
  wire  ge = ~lt; // @[src/main/scala/backend/execute/BRU.scala 37:13]
  wire  ltu = io_rs1 < io_rs2; // @[src/main/scala/backend/execute/BRU.scala 38:18]
  wire  geu = ~ltu; // @[src/main/scala/backend/execute/BRU.scala 39:13]
  wire  _branchTaken_T = io_uop_ctrl_bruOp == 4'h1; // @[src/main/scala/backend/execute/BRU.scala 43:10]
  wire  _branchTaken_T_1 = io_uop_ctrl_bruOp == 4'h2; // @[src/main/scala/backend/execute/BRU.scala 44:10]
  wire  _branchTaken_T_2 = io_uop_ctrl_bruOp == 4'h3; // @[src/main/scala/backend/execute/BRU.scala 45:10]
  wire  _branchTaken_T_3 = io_uop_ctrl_bruOp == 4'h4; // @[src/main/scala/backend/execute/BRU.scala 46:10]
  wire  _branchTaken_T_4 = io_uop_ctrl_bruOp == 4'h5; // @[src/main/scala/backend/execute/BRU.scala 47:10]
  wire  _branchTaken_T_5 = io_uop_ctrl_bruOp == 4'h6; // @[src/main/scala/backend/execute/BRU.scala 48:10]
  wire  _branchTaken_T_6 = io_uop_ctrl_bruOp == 4'h7; // @[src/main/scala/backend/execute/BRU.scala 49:10]
  wire  _branchTaken_T_7 = io_uop_ctrl_bruOp == 4'h8; // @[src/main/scala/backend/execute/BRU.scala 50:10]
  wire  _branchTaken_T_8 = io_uop_ctrl_bruOp == 4'h9; // @[src/main/scala/backend/execute/BRU.scala 51:10]
  wire  _branchTaken_T_10 = _branchTaken_T_7 ? ltu : _branchTaken_T_8 & geu; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire  _branchTaken_T_11 = _branchTaken_T_6 ? ge : _branchTaken_T_10; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire  _branchTaken_T_12 = _branchTaken_T_5 ? lt : _branchTaken_T_11; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire  _branchTaken_T_13 = _branchTaken_T_4 ? ne : _branchTaken_T_12; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire  _branchTaken_T_14 = _branchTaken_T_3 ? eq : _branchTaken_T_13; // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire  branchTaken = _branchTaken_T | (_branchTaken_T_1 | (_branchTaken_T_2 | _branchTaken_T_14)); // @[src/main/scala/chisel3/util/Mux.scala 141:16]
  wire [31:0] linkResult = io_uop_pc + 32'h4; // @[src/main/scala/backend/execute/BRU.scala 64:23]
  assign io_result = _branchTaken_T_2 | _branchTaken_T ? linkResult : 32'h0; // @[src/main/scala/backend/execute/BRU.scala 66:19]
  assign io_redirect_valid = io_valid & io_isBranch & branchTaken; // @[src/main/scala/backend/execute/BRU.scala 74:48]
  assign io_redirect_bits_robIdx = io_uop_robIdxFull[5:0]; // @[src/main/scala/backend/execute/BRU.scala 76:27]
  assign io_isBranch = io_uop_ctrl_bruOp != 4'h0; // @[src/main/scala/backend/execute/BRU.scala 71:21]
endmodule
