// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vsimu_top.h for the primary calling header

#ifndef VERILATED_VSIMU_TOP___024ROOT_H_
#define VERILATED_VSIMU_TOP___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_save.h"
class Vsimu_top___024unit;


class Vsimu_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vsimu_top___024root final : public VerilatedModule {
  public:
    // CELLS
    Vsimu_top___024unit* __PVT____024unit;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(pclk,0,0);
        VL_IN8(penable,0,0);
        VL_IN8(pwrite,0,0);
        VL_IN8(aclk,0,0);
        CData/*0:0*/ NAND_top__DOT__HIT0;
        CData/*0:0*/ NAND_top__DOT__HIT1;
        CData/*0:0*/ NAND_top__DOT__HIT2;
        CData/*0:0*/ NAND_top__DOT__HIT3;
        CData/*0:0*/ NAND_top__DOT__HIT6;
        CData/*0:0*/ NAND_top__DOT__HIT7;
        CData/*0:0*/ NAND_top__DOT__HIT8;
        CData/*0:0*/ NAND_top__DOT__HIT9;
        CData/*0:0*/ NAND_top__DOT__HIT10;
        CData/*0:0*/ NAND_top__DOT__HIT11;
        CData/*0:0*/ NAND_top__DOT__NAND_HIT;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_wvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_arvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__apb_s_wready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_fifo_empty;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_fifo_full;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_fifo_full;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_resp_prog;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__axi_s_sel_rd;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__axi_s_sel_wr;
        VL_IN8(nand_type,1,0);
        VL_IN8(prst_,0,0);
        VL_IN8(psel,0,0);
        VL_OUT8(NAND_CE_o,3,0);
        VL_OUT8(NAND_REQ,0,0);
        VL_IN8(NAND_I,7,0);
        VL_OUT8(NAND_O,7,0);
        VL_OUT8(NAND_EN_,0,0);
        VL_OUT8(NAND_ALE,0,0);
        VL_OUT8(NAND_CLE,0,0);
        VL_OUT8(NAND_WR_,0,0);
        VL_OUT8(NAND_RD_,0,0);
        VL_IN8(NAND_IORDY_i,3,0);
        VL_OUT8(nand_int,0,0);
        VL_IN8(aresetn,0,0);
        VL_IN8(enable_delay,0,0);
        VL_OUT8(ram_ren,0,0);
        VL_OUT8(ram_wen,3,0);
        VL_OUT8(debug0_wb_rf_wen,0,0);
        VL_OUT8(debug0_wb_rf_wnum,4,0);
        VL_OUT8(open_trace,0,0);
        VL_OUT8(num_monitor,0,0);
        VL_OUT8(confreg_uart_data,7,0);
        VL_OUT8(write_uart_valid,0,0);
        VL_INOUT8(uart_rx,0,0);
        VL_INOUT8(uart_tx,0,0);
        VL_OUT8(led_rg0,1,0);
        VL_OUT8(led_rg1,1,0);
        VL_OUT8(num_csn,7,0);
        VL_OUT8(num_a_g,6,0);
        VL_IN8(__SYM__switch,7,0);
        VL_OUT8(btn_key_col,3,0);
        VL_IN8(btn_key_row,3,0);
        VL_IN8(btn_step,1,0);
        CData/*0:0*/ uart_rx__en0;
        CData/*4:0*/ NAND_top__DOT__NAND_STATE;
        CData/*0:0*/ NAND_top__DOT__nand_clr_ack;
        CData/*0:0*/ NAND_top__DOT__NAND_DONE;
        CData/*0:0*/ NAND_top__DOT__NAND_CE_;
        CData/*0:0*/ NAND_top__DOT__NANDtag;
    };
    struct {
        CData/*0:0*/ NAND_top__DOT__NAND_IORDY;
        CData/*0:0*/ NAND_top__DOT__NAND_DMA_REQ;
        CData/*0:0*/ NAND_top__DOT__nand_cmd_valid;
        CData/*7:0*/ NAND_top__DOT__status;
        CData/*1:0*/ NAND_top__DOT__nand_number;
        CData/*1:0*/ NAND_top__DOT__ADDR_pointer;
        CData/*2:0*/ NAND_top__DOT__NAND_ADDR_COUNT;
        CData/*7:0*/ NAND_top__DOT__WAIT_NUM;
        CData/*7:0*/ NAND_top__DOT__HOLD_NUM;
        CData/*7:0*/ NAND_top__DOT__COMMAND;
        CData/*4:0*/ NAND_top__DOT__PRE_STATE;
        CData/*2:0*/ NAND_top__DOT__READ_ID_NUM;
        CData/*0:0*/ NAND_top__DOT__NAND_GO;
        CData/*0:0*/ NAND_top__DOT__NAND_ACK;
        CData/*0:0*/ NAND_top__DOT__DMA_OP_DONE;
        CData/*0:0*/ NAND_top__DOT__ERASE_SERIAL;
        CData/*0:0*/ NAND_top__DOT__now_up_half;
        CData/*0:0*/ NAND_top__DOT__now_oob;
        CData/*0:0*/ NAND_top__DOT____VdfgTmp_h1f93f44c__0;
        CData/*0:0*/ NAND_top__DOT____VdfgTmp_hda4dca10__0;
        CData/*0:0*/ NAND_top__DOT____VdfgTmp_h1fdf66ec__0;
        CData/*0:0*/ NAND_top__DOT____VdfgTmp_hdee97012__0;
        CData/*0:0*/ NAND_top__DOT____VdfgTmp_hc546cbe1__0;
        CData/*0:0*/ NAND_top__DOT____VdfgTmp_heedab63f__0;
        CData/*0:0*/ NAND_top__DOT____VdfgTmp_ha1106bbf__0;
        CData/*0:0*/ simu_top__DOT__uart_rx__out__strong__out3;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_awready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_wready;
        CData/*3:0*/ simu_top__DOT__soc__DOT__m0_bid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__m0_bresp;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_bvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_bready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_arready;
        CData/*3:0*/ simu_top__DOT__soc__DOT__m0_rid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__m0_rresp;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_rlast;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_rvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_rready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__s0_wready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_s_wready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__apb_s_awready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__apb_s_bvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__apb_s_arready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__apb_s_rlast;
        CData/*0:0*/ simu_top__DOT__soc__DOT__apb_s_rvalid;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_s_ram_wen;
        CData/*0:0*/ simu_top__DOT__soc__DOT__UART_RI;
        CData/*0:0*/ simu_top__DOT__soc__DOT__uart0_int;
        CData/*0:0*/ simu_top__DOT__soc__DOT__uart0_txd_oe;
        CData/*3:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar_io_out_w_data_wstrb;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar_io_out_w_data_wlast;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar_io_out_w_wready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar_io_out_r_data_rvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar_io_out_b_data_bvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__ar_arbiter_io_in_0_ready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__ar_arbiter_io_in_0_valid;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__ar_arbiter_io_out_bits_arlen;
        CData/*2:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__ar_arbiter_io_out_bits_arsize;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__ar_arbiter_io_out_bits_arburst;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__aw_arbiter_io_in_1_ready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__aw_master_valid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__aw_master_idx;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT___GEN_71;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe_io_cpu_req_valid;
    };
    struct {
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe_io_cpu_resp_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe_io_miss_req_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe_io_miss_resp_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe_io_replacer_touch_valid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe_io_replacer_touch_way;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit_io_meta_write_valid;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit_io_meta_write_idx;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit_io_meta_write_way;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit_io_axi_r_in_rvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe__DOT__s0_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe__DOT__s1_valid;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe__DOT__s1_idx;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe__DOT___GEN_4;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe__DOT__s2_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe__DOT__s2_hit;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe__DOT__tag_hits_2;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe__DOT__tag_hits_3;
        CData/*3:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe__DOT___s1_hit_T;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe__DOT__s1_hit_way_hi_1;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe__DOT__s1_hit_way_lo_1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe__DOT___GEN_18;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe__DOT___GEN_35;
        CData/*2:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__state;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__req_idx;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__req_victim_way;
        CData/*4:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__data_count;
        CData/*4:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___data_count_T_1;
        CData/*2:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_42;
        CData/*2:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_86;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_0_valid_MPORT_1_data;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_0_valid_MPORT_en_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_0_valid_current_data_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_0_valid_current_data_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_0_tag_MPORT_en_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_0_tag_current_data_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_0_tag_current_data_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_1_valid_MPORT_1_data;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_1_valid_MPORT_en_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_1_valid_current_data_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_1_valid_current_data_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_1_tag_MPORT_en_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_1_tag_current_data_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_1_tag_current_data_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_2_valid_MPORT_1_data;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_2_valid_MPORT_en_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_2_valid_current_data_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_2_valid_current_data_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_2_tag_MPORT_en_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_2_tag_current_data_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_2_tag_current_data_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_3_valid_MPORT_1_data;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_3_valid_MPORT_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_3_valid_MPORT_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_3_valid_current_data_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_3_valid_current_data_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_3_tag_MPORT_en_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_3_tag_current_data_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_3_tag_current_data_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_0_MPORT_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_0_MPORT_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_0_current_data_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_0_current_data_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_1_MPORT_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_1_MPORT_addr_pipe_0;
    };
    struct {
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_1_current_data_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_1_current_data_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_2_MPORT_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_2_MPORT_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_2_current_data_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_2_current_data_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_3_MPORT_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_3_MPORT_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_3_current_data_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_3_current_data_addr_pipe_0;
        CData/*2:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__replacer__DOT__plruTree_currentPLRU_data;
        CData/*2:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__replacer__DOT__plruTree_currentPLRU_1_data;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__replacer__DOT__plruTree_currentPLRU_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__replacer__DOT__plruTree_currentPLRU_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__replacer__DOT__plruTree_currentPLRU_1_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__replacer__DOT__plruTree_currentPLRU_1_addr_pipe_0;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__replacer__DOT__victimRespReg;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__fetch_unit__DOT__pc_valid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__fetch_unit__DOT__fetch_state;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__fetch_unit__DOT___GEN_5;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__difftest__DOT__cmt_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_ar_disable;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_aw_disable;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_no_delay;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_short_delay;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_w_disable;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT____VdfgTmp_h343203d2__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT____VdfgTmp_h758095b7__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT____VdfgTmp_h75ade73a__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT____VdfgTmp_h4b9dd77d__0;
        CData/*3:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_bid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_bresp;
        CData/*3:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_rid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_rresp;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_rlast;
        CData/*3:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_bid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_bresp;
        CData/*3:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_rid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_rresp;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_rlast;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_data_s_hit;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_addr_hit;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_addr_hit;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_resp_s_hit;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_awready;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_wready;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_bvalid;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_arready;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_rlast;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_rvalid;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_awvalid;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_wvalid;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_bready;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_arvalid;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_rready;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_sel_group_0;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_sel_group_1;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__bvalid_group_0;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_sel_group_0;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_sel_group_1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_fifo_empty;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_dir_del;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_data_dir;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_addr_dir;
    };
    struct {
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_resp_pre_sel;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_resp_sel_reg;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_resp_sel;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_data_sel;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_dir_ins;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_addr_dir;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_data_pre_sel;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT____Vlvbound_hfc587a0d__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT____Vlvbound_hd5ae529f__1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT____Vlvbound_hc31fd36f__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT____Vlvbound_hdb504bf8__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT____Vlvbound_h363acc24__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT____Vlvbound_h4bcda73f__1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT____VdfgTmp_h58d65b4b__0;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_fifo__DOT__wr_ptr;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_fifo__DOT__rd_ptr;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_fifo__DOT__wr_ptr;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_fifo__DOT__rd_ptr;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_rw_dma;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_psel_dma;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_enab_dma;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_valid_dma;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__dma_grant;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__dma_ack_i;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_psel_cpu;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_enab_cpu;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_datai_cpu;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_datao_cpu;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_word_trans_cpu;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_valid_cpu;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_clk_dma;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_reset_n_dma;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_uart0_ack;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_uart0_rw;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_uart0_datai;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_uart0_datao;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_nand_req;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_nand_ack;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_nand_rw;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_nand_enab;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_nand_psel;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__reg_ready;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__csr_rw_sm;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__csr_rw_sm_nxt;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__axi_s_w_id;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__axi_s_r_id;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__axi_s_rstrb;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__apb_s_wstrb;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__rd_count;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__apb_rd_size;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__apb_wr_size;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_apb_mux16__DOT__apb_psel;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_apb_mux16__DOT__apb_enab;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__we;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__re;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__rx_en;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__tx2rx_en;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT____VdfgTmp_hf971e7f2__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__enable;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__srx_pad;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ier;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__iir;
        CData/*1:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__fcr;
        CData/*4:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__mcr;
    };
    struct {
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__infrared;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rx_pol;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lcr;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__msr;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__start_dlc;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr_mask_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__msi_reset;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__trigger_level;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rx_reset;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__tx_reset;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__sclk_reg;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__sclk_en_reg;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__mode_reg;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__fi_di_reg;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__sclk_count;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__repeat_reg;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__tx_en;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr5;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr6;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr7;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr0r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr1r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr2r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr3r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr4r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr5r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr6r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr7r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr_mask;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rls_int;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rda_int;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ti_int;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__thre_int;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ms_int;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__tf_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rf_pop;
        CData/*4:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rf_count;
        CData/*4:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__tf_count;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__tstate;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rstate;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__block_cnt;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__block_value;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__max_repeat_time;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__serial_out;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__serial_in;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rf_overrun;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rf_push_pulse;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT____Vcellinp__receiver__enable;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr_mask_condition;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__iir_read;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__msr_read;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__fifo_read;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__delayed_modem_signals;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr0_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr1_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr2_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr3_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr4_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr5_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr6_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr7_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__M_toggle;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rls_int_d;
    };
    struct {
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__thre_int_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ms_int_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ti_int_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rda_int_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rls_int_pnd;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rda_int_pnd;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__thre_int_pnd;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ms_int_pnd;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ti_int_pnd;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__d1_fifo_read;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT____VdfgTmp_h704d72b7__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT____VdfgTmp_hcfa3840f__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT____VdfgTmp_h882fb5aa__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT____VdfgTmp_hce37628e__0;
        CData/*4:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__counter;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__bit_counter;
        CData/*6:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__shift_out;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__stx_o_tmp;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__parity_xor;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__tf_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__bit_out;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__tx_error;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__error_time;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__tf_data_out;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__tf_overrun;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__tf_data_bak;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT____VdfgTmp_hd44064a6__0;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__fifo_tx__DOT__top;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__fifo_tx__DOT__bottom;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__fifo_tx__DOT__top_plus_1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__i_uart_sync_flops__DOT__flop_0;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rcounter16;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rbit_counter;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rshift;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rparity;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rparity_error;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rframing_error;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rbit_in;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rparity_xor;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__counter_b;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rf_push_q;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rf_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rcounter16_eq_7;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rcounter16_eq_0;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rcounter16_minus_1;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__data8_out;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__top;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__bottom;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__top_plus_1;
        CData/*1:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_arburst;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_arid;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_arlen;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_arlen_last;
        CData/*2:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_arsize;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_queue_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_queue_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_queue_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_en;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_rcur;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_rid;
    };
    struct {
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_rlast;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_rvalid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_awburst;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_awid;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_awlen;
        CData/*2:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_awsize;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_queue_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_queue_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_queue_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_allow_out;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_data;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_pop;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_queue_datas;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_queue_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_queue_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_queue_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_en;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_go;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_wlast;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_wstrb;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_wvalid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_arburst;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_arid;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_arlen;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_arlen_last;
        CData/*2:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_arsize;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_queue_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_queue_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_queue_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_valid;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_rcur;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_rid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_rlast;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_rvalid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_awburst;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_awid;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_awlen;
        CData/*2:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_awsize;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_queue_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_queue_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_queue_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_allow_out;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_data;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_pop;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_queue_datas;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_queue_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_queue_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_queue_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_en;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_go;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_wlast;
    };
    struct {
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_wstrb;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_wvalid;
        CData/*7:0*/ simu_top__DOT__soc__DOT__confreg__DOT__confreg_uart_data;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__confreg_uart_valid;
        CData/*7:0*/ simu_top__DOT__soc__DOT__confreg__DOT__virtual_uart_data;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__open_trace;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__num_monitor;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer_begin;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer_begin_r1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer_begin_r2;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer_begin_r3;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer_end_r1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer_end_r2;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_uart_valid;
        CData/*2:0*/ simu_top__DOT__soc__DOT__confreg__DOT__state;
        CData/*2:0*/ simu_top__DOT__soc__DOT__confreg__DOT__next_state;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__key_flag;
        CData/*3:0*/ simu_top__DOT__soc__DOT__confreg__DOT__state_count;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__btn_step0_r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__btn_step1_r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__step0_flag;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__step1_flag;
        CData/*3:0*/ simu_top__DOT__soc__DOT__confreg__DOT__scan_data;
        CData/*2:0*/ __VdfgTmp_hcd04e225__0;
        CData/*2:0*/ __Vfunc_simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__get_num__7__Vfuncout;
        CData/*2:0*/ __Vfunc_simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__get_num__7__valid;
        CData/*2:0*/ __Vfunc_simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__get_num__7__pre_num;
        CData/*2:0*/ __Vfunc_simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__get_num__8__Vfuncout;
        CData/*2:0*/ __Vfunc_simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__get_num__8__valid;
        CData/*2:0*/ __Vfunc_simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__get_num__8__pre_num;
        CData/*4:0*/ __Vtableidx2;
        CData/*1:0*/ __Vtableidx4;
        CData/*7:0*/ __Vtableidx5;
        CData/*7:0*/ __Vtableidx8;
        CData/*4:0*/ __Vtrigprevexpr___TOP__simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_addr_hit__0;
        CData/*0:0*/ __VstlDidInit;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*4:0*/ __Vtrigprevexpr___TOP__simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_addr_hit__1;
        CData/*0:0*/ __Vtrigprevexpr___TOP__pclk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__aclk__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        VL_IN16(ADDR,10,0);
        VL_OUT16(led,15,0);
        SData/*13:0*/ NAND_top__DOT__nand_addr_c;
        SData/*15:0*/ NAND_top__DOT__nand_timing;
        SData/*13:0*/ NAND_top__DOT__WRITE_MAX_COUNT;
        SData/*13:0*/ NAND_top__DOT__READ_MAX_COUNT;
        SData/*13:0*/ NAND_top__DOT__data_count;
        SData/*15:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__dlc;
        SData/*9:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__counter_t;
        SData/*8:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__M_cnt;
        SData/*8:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__M_next;
        SData/*10:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rf_data_in;
        SData/*9:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__toc_value;
        SData/*15:0*/ simu_top__DOT__soc__DOT__confreg__DOT__btn_key_r;
        SData/*15:0*/ simu_top__DOT__soc__DOT__confreg__DOT__btn_key_tmp;
        VL_IN(DAT_I,31,0);
        VL_OUT(DAT_O,31,0);
        VL_IN(random_seed,22,0);
        VL_OUT(ram_raddr,31,0);
        VL_IN(ram_rdata,31,0);
    };
    struct {
        VL_OUT(ram_waddr,31,0);
        VL_OUT(ram_wdata,31,0);
        VL_OUT(debug0_wb_pc,31,0);
        VL_OUT(debug0_wb_rf_wdata,31,0);
        VL_OUT(num_data,31,0);
        VL_OUTW(uart_ctr_bus,127,0,4);
        IData/*31:0*/ NAND_top__DOT__REG_DAT_T;
        IData/*24:0*/ NAND_top__DOT__nand_addr_r;
        IData/*31:0*/ NAND_top__DOT__nand_op_num;
        IData/*31:0*/ NAND_top__DOT__nand_parameter;
        IData/*31:0*/ NAND_top__DOT__nand_ce_map0;
        IData/*31:0*/ NAND_top__DOT__nand_ce_map1;
        IData/*31:0*/ NAND_top__DOT__nand_rdy_map0;
        IData/*31:0*/ NAND_top__DOT__nand_rdy_map1;
        IData/*31:0*/ NAND_top__DOT__nand_command;
        IData/*31:0*/ NAND_top__DOT__NAND_OP_NUM;
        IData/*31:0*/ NAND_top__DOT__NAND_DAT_O_RD;
        IData/*31:0*/ NAND_top__DOT__NAND_DAT_I_WR;
        IData/*31:0*/ simu_top__DOT__soc__DOT__m0_rdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar_io_out_w_data_wdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__ar_arbiter_io_out_bits_araddr;
        VlWide<16>/*511:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit_io_data_write_data;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit_io_axi_r_in_rdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe__DOT__s0_addr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe__DOT__s1_addr;
        IData/*17:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe__DOT__s1_tag;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe__DOT__s2_addr;
        VlWide<16>/*511:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__mainPipe__DOT__s2_data;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__req_addr;
        IData/*17:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__req_tag;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__data_buffer_0;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__data_buffer_1;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__data_buffer_2;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__data_buffer_3;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__data_buffer_4;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__data_buffer_5;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__data_buffer_6;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__data_buffer_7;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__data_buffer_8;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__data_buffer_9;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__data_buffer_10;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__data_buffer_11;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__data_buffer_12;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__data_buffer_13;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__data_buffer_14;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT__data_buffer_15;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_8;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_9;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_10;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_11;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_12;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_13;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_14;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_15;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_16;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_17;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_18;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_19;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_20;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_21;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_22;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_23;
        VlWide<16>/*511:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___io_data_write_data_T;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_57;
    };
    struct {
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_58;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_59;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_60;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_61;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_62;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_63;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_64;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_65;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_66;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_67;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_68;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_69;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_70;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_71;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__missUnit__DOT___GEN_72;
        IData/*17:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_0_tag_MPORT_1_data;
        IData/*17:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_1_tag_MPORT_1_data;
        IData/*17:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_2_tag_MPORT_1_data;
        IData/*17:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_3_tag_MPORT_1_data;
        VlWide<16>/*511:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_0_MPORT_1_data;
        VlWide<16>/*511:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_1_MPORT_1_data;
        VlWide<16>/*511:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_2_MPORT_1_data;
        VlWide<16>/*511:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_3_MPORT_1_data;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__fetch_unit__DOT__pc_reg;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__fetch_unit__DOT___GEN_6;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__difftest__DOT__cmt_inst;
        IData/*22:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_random;
        IData/*22:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_random_next;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_rdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_rdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__w_addr_dir_int;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_addr_hit_int;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_addr_dir_int;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_fifo__DOT__i;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_fifo__DOT__i;
        IData/*19:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_addr_dma;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_wdata_dma;
        IData/*23:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_high_24b_wr;
        IData/*19:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_uart0_addr;
        IData/*19:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_nand_addr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_nand_datai;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_nand_datao;
        IData/*19:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__axi_s_req_addr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__reg_datai_32;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__reg_datao_32;
        IData/*23:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__dl;
        IData/*31:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_araddr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_araddr_next;
        IData/*31:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_awaddr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_awaddr_next;
        IData/*31:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_wdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_araddr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_araddr_next;
        IData/*31:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_awaddr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_awaddr_next;
        IData/*31:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_wdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr0;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr1;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr2;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr3;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr4;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr5;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr6;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr7;
    };
    struct {
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__led_data;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__led_rg0_data;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__led_rg1_data;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__num_data;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__timer_r2;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__simu_flag;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__io_simu;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__conf_rdata_reg;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__conf_wdata_r;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__conf_wdata_r1;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__conf_wdata_r2;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__timer_r1;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__timer;
        IData/*19:0*/ simu_top__DOT__soc__DOT__confreg__DOT__key_count;
        IData/*19:0*/ simu_top__DOT__soc__DOT__confreg__DOT__step0_count;
        IData/*19:0*/ simu_top__DOT__soc__DOT__confreg__DOT__step1_count;
        IData/*19:0*/ simu_top__DOT__soc__DOT__confreg__DOT__count;
        IData/*31:0*/ __VactIterCount;
        QData/*37:0*/ NAND_top__DOT__addr_in_die;
        QData/*47:0*/ NAND_top__DOT__ID_INFORM;
        QData/*37:0*/ NAND_top__DOT__NAND_ADDR;
        QData/*63:0*/ simu_top__DOT__soc__DOT__cpu__DOT__reg_;
        QData/*63:0*/ simu_top__DOT__soc__DOT__cpu__DOT___reg_T_1;
        QData/*63:0*/ simu_top__DOT__soc__DOT__cpu__DOT__difftest__DOT__cmt_pc;
        QData/*63:0*/ simu_top__DOT__soc__DOT__cpu__DOT__difftest__DOT__cycleCnt;
        QData/*63:0*/ simu_top__DOT__soc__DOT__cpu__DOT__difftest__DOT__instrCnt;
        QData/*63:0*/ simu_top__DOT__soc__DOT__cpu__DOT__difftest__DOT___cycleCnt_T_1;
        QData/*63:0*/ simu_top__DOT__soc__DOT__cpu__DOT__difftest__DOT___instrCnt_T_1;
        QData/*44:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_push_data;
        QData/*44:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_queue_datas;
        QData/*44:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_queue_datas;
        QData/*44:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_queue_datas;
        QData/*44:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_queue_datas;
        VlUnpacked<CData/*0:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_0_valid;
        VlUnpacked<IData/*17:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_0_tag;
        VlUnpacked<CData/*0:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_1_valid;
        VlUnpacked<IData/*17:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_1_tag;
        VlUnpacked<CData/*0:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_2_valid;
        VlUnpacked<IData/*17:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_2_tag;
        VlUnpacked<CData/*0:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_3_valid;
        VlUnpacked<IData/*17:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__metaArray__DOT__metaArray_3_tag;
        VlUnpacked<VlWide<16>/*511:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_0;
        VlUnpacked<VlWide<16>/*511:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_1;
        VlUnpacked<VlWide<16>/*511:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_2;
        VlUnpacked<VlWide<16>/*511:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__dataArray__DOT__dataArray_3;
        VlUnpacked<CData/*2:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__replacer__DOT__plruTree;
        VlUnpacked<CData/*3:0*/, 5> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_bid;
        VlUnpacked<CData/*1:0*/, 5> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_bresp;
        VlUnpacked<CData/*3:0*/, 5> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_rid;
        VlUnpacked<IData/*31:0*/, 5> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_rdata;
        VlUnpacked<CData/*1:0*/, 5> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_rresp;
        VlUnpacked<CData/*4:0*/, 5> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__BASE_ADDR;
        VlUnpacked<CData/*2:0*/, 2> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_fifo__DOT__fifo_ram;
        VlUnpacked<CData/*2:0*/, 2> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_fifo__DOT__fifo_ram;
        VlUnpacked<CData/*7:0*/, 16> simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__fifo_tx__DOT__tfifo__DOT__ram;
        VlUnpacked<CData/*2:0*/, 16> simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__fifo;
        VlUnpacked<CData/*7:0*/, 16> simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__rfifo__DOT__ram;
        VlUnpacked<CData/*0:0*/, 6> __Vm_traceActivity;
    };
    VlTriggerVec<2> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<3> __VactTriggered;
    VlTriggerVec<3> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vsimu_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vsimu_top___024root(Vsimu_top__Syms* symsp, const char* v__name);
    ~Vsimu_top___024root();
    VL_UNCOPYABLE(Vsimu_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
    void __Vserialize(VerilatedSerialize& os);
    void __Vdeserialize(VerilatedDeserialize& os);
};


#endif  // guard
