// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vsimu_top.h for the primary calling header

#ifndef VERILATED_VSIMU_TOP___024ROOT_H_
#define VERILATED_VSIMU_TOP___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_save.h"
class Vsimu_top___024unit;


class Vsimu_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vsimu_top___024root final {
  public:
    // CELLS
    Vsimu_top___024unit* __PVT____024unit;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(aclk,0,0);
        VL_IN8(pclk,0,0);
        VL_IN8(aresetn,0,0);
        VL_IN8(enable_delay,0,0);
        VL_OUT8(ram_ren,0,0);
        VL_OUT8(ram_wen,3,0);
        VL_OUT8(debug0_wb_rf_wen,0,0);
        VL_OUT8(debug0_wb_rf_wnum,4,0);
        VL_OUT8(open_trace,0,0);
        VL_OUT8(num_monitor,0,0);
        VL_OUT8(confreg_uart_data,7,0);
        VL_OUT8(write_uart_valid,0,0);
        VL_INOUT8(uart_rx,0,0);
        VL_INOUT8(uart_tx,0,0);
        VL_OUT8(led_rg0,1,0);
        VL_OUT8(led_rg1,1,0);
        VL_OUT8(num_csn,7,0);
        VL_OUT8(num_a_g,6,0);
        VL_IN8(__SYM__switch,7,0);
        VL_OUT8(btn_key_col,3,0);
        VL_IN8(btn_key_row,3,0);
        VL_IN8(btn_step,1,0);
        VL_IN8(nand_type,1,0);
        VL_IN8(prst_,0,0);
        VL_IN8(psel,0,0);
        VL_IN8(penable,0,0);
        VL_IN8(pwrite,0,0);
        VL_OUT8(NAND_CE_o,3,0);
        VL_OUT8(NAND_REQ,0,0);
        VL_IN8(NAND_I,7,0);
        VL_OUT8(NAND_O,7,0);
        VL_OUT8(NAND_EN_,0,0);
        VL_OUT8(NAND_ALE,0,0);
        VL_OUT8(NAND_CLE,0,0);
        VL_OUT8(NAND_WR_,0,0);
        VL_OUT8(NAND_RD_,0,0);
        VL_IN8(NAND_IORDY_i,3,0);
        VL_OUT8(nand_int,0,0);
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_awready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_wready;
        CData/*3:0*/ simu_top__DOT__soc__DOT__m0_bid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__m0_bresp;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_bvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_arready;
        CData/*3:0*/ simu_top__DOT__soc__DOT__m0_rid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__m0_rresp;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_rlast;
        CData/*0:0*/ simu_top__DOT__soc__DOT__m0_rvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__apb_s_awready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__apb_s_wready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__apb_s_bvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__apb_s_arready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__apb_s_rlast;
        CData/*0:0*/ simu_top__DOT__soc__DOT__apb_s_rvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__UART_RI;
        CData/*0:0*/ simu_top__DOT__soc__DOT__uart0_int;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__io_in_icache_ar_out_arvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__io_in_icache_r_in_rvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__io_in_dcache_ar_out_arvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__io_in_dcache_r_in_rvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__io_in_uncache1_ar_out_arvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__io_in_uncache1_r_in_rvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__io_in_uncache2_r_in_rvalid;
        CData/*2:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__io_out_ar_out_arsize;
    };
    struct {
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__io_out_ar_out_arburst;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__io_out_ar_arready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__io_out_aw_awready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__io_out_w_wready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__io_out_r_in_rvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__io_out_b_in_bvalid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__sel_idx;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__io_cpu_if_resp_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__cache_tag_rd_tag_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__cache_tag_rd_tag_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__cache_valid_rd_valid_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__cache_valid_rd_valid_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__cache_data_io_cpu_if_resp_data_MPORT_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__cache_data_io_cpu_if_resp_data_MPORT_addr_pipe_0;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__state;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT___GEN_34;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__dcache__DOT__io_cpu_if_resp_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__dcache__DOT__cache_tag_rd_tag_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__dcache__DOT__cache_tag_rd_tag_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__dcache__DOT__cache_valid_rd_valid_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__dcache__DOT__cache_valid_rd_valid_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__dcache__DOT__cache_data_io_cpu_if_resp_data_MPORT_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__dcache__DOT__cache_data_io_cpu_if_resp_data_MPORT_addr_pipe_0;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__dcache__DOT__state;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__dcache__DOT___GEN_34;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache1__DOT__io_cpu_if_resp_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache1__DOT__cache_tag_rd_tag_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache1__DOT__cache_tag_rd_tag_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache1__DOT__cache_valid_rd_valid_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache1__DOT__cache_valid_rd_valid_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache1__DOT__cache_data_io_cpu_if_resp_data_MPORT_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache1__DOT__cache_data_io_cpu_if_resp_data_MPORT_addr_pipe_0;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache1__DOT__state;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache1__DOT___GEN_34;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache2__DOT__io_cpu_if_resp_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache2__DOT__cache_tag_rd_tag_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache2__DOT__cache_tag_rd_tag_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache2__DOT__cache_valid_rd_valid_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache2__DOT__cache_valid_rd_valid_addr_pipe_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache2__DOT__cache_data_io_cpu_if_resp_data_MPORT_en_pipe_0;
        CData/*7:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache2__DOT__cache_data_io_cpu_if_resp_data_MPORT_addr_pipe_0;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache2__DOT__state;
        CData/*1:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache2__DOT___GEN_34;
        CData/*0:0*/ simu_top__DOT__soc__DOT__cpu__DOT__difftest__DOT__cmt_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT__s_arvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT__s_rready;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_ar_disable;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_aw_disable;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_no_delay;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_short_delay;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_w_disable;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT____VdfgRegularize_ha6db628c_0_2;
        CData/*0:0*/ simu_top__DOT__soc__DOT__delay__DOT____VdfgRegularize_ha6db628c_0_5;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT____Vlvbound_h63b02204__1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT____Vlvbound_hb47bec07__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT____Vlvbound_h326270fe__0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT____Vlvbound_hefbc5fe9__0;
        CData/*3:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_bid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_bresp;
        CData/*3:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_rid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_rresp;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_rlast;
        CData/*3:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_bid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_bresp;
    };
    struct {
        CData/*3:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_rid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_rresp;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_rlast;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_data_s_hit;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_addr_hit;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_resp_s_hit;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_awready;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_wready;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_bvalid;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_arready;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_rlast;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_rvalid;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_awvalid;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_wvalid;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_bready;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_arvalid;
        CData/*4:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_rready;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_sel_group_0;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_sel_group_1;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__bvalid_group_0;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_sel_group_0;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_sel_group_1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_fifo_empty;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_fifo_full;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_fifo_empty;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_fifo_full;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_data_dir;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_addr_dir;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_resp_pre_sel;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_resp_prog;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_resp_sel_reg;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_resp_sel;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_data_sel;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_dir_ins;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_addr_dir;
        CData/*2:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_data_pre_sel;
        CData/*0:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT____VdfgRegularize_h9b44d7d4_0_3;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_fifo__DOT__wr_ptr;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_fifo__DOT__rd_ptr;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_fifo__DOT__wr_ptr;
        CData/*1:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_fifo__DOT__rd_ptr;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_rw_dma;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_psel_dma;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_enab_dma;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_valid_dma;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__dma_grant;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__dma_ack_i;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_psel_cpu;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_enab_cpu;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_datai_cpu;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_clk_dma;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_reset_n_dma;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_uart0_ack;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_uart0_rw;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_uart0_datai;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_nand_req;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_nand_ack;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_nand_rw;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_nand_enab;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_nand_psel;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__apb_valid_cpu;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__apb_word_trans;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__reg_datao;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__reg_ready;
    };
    struct {
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__axi_s_sel_rd;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__axi_s_sel_wr;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__csr_rw_sm;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__csr_rw_sm_nxt;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__axi_s_w_id;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__axi_s_r_id;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__axi_s_rstrb;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__apb_s_wstrb;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__rd_count;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__apb_rd_size;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__apb_wr_size;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_apb_mux16__DOT__apb_ack;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_apb_mux16__DOT__apb_psel;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_apb_mux16__DOT__apb_enab;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_apb_mux16__DOT__apb_datao;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__tx2rx_en;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT____VdfgRegularize_h74633bcc_0_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__we;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__re;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__usart_mode;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rx_en;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__enable;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__srx_pad;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ier;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__iir;
        CData/*1:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__fcr;
        CData/*4:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__mcr;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__infrared;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rx_pol;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lcr;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__msr;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__start_dlc;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr_mask_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__msi_reset;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__trigger_level;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rx_reset;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__tx_reset;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__sclk_reg;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__sclk_en_reg;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__mode_reg;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__fi_di_reg;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__sclk_count;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__repeat_reg;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr2;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr3;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr4;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr5;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr6;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr7;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr0r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr1r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr2r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr3r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr4r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr5r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr6r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr7r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rls_int;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rda_int;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ti_int;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__thre_int;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ms_int;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rf_pop;
    };
    struct {
        CData/*4:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rf_count;
        CData/*4:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__tf_count;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__tstate;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rstate;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__block_cnt;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__block_value;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__serial_out;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rf_overrun;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT____Vcellinp__receiver__enable;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr_mask_condition;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__iir_read;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__msr_read;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__fifo_read;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__delayed_modem_signals;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr0_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr1_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr2_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr3_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr4_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr5_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr6_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__lsr7_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__M_toggle;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rls_int_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__thre_int_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ms_int_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ti_int_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rda_int_d;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rls_int_pnd;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__rda_int_pnd;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__thre_int_pnd;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ms_int_pnd;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__ti_int_pnd;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__d1_fifo_read;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT____VdfgRegularize_hf5566834_0_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT____VdfgRegularize_hf5566834_0_2;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT____VdfgRegularize_hf5566834_0_3;
        CData/*4:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__counter;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__bit_counter;
        CData/*6:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__shift_out;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__stx_o_tmp;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__parity_xor;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__tf_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__bit_out;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__tx_error;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__error_time;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__tf_data_out;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__tf_overrun;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__tf_data_bak;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT____VdfgRegularize_h6d58cdb3_0_0;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__fifo_tx__DOT__top;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__fifo_tx__DOT__bottom;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__fifo_tx__DOT__top_plus_1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__fifo_tx__DOT__tfifo__DOT__we;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__i_uart_sync_flops__DOT__flop_0;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__srx_pad_i;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__lsr_mask;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rcounter16;
        CData/*2:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rbit_counter;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rshift;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rparity;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rparity_error;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rframing_error;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rbit_in;
    };
    struct {
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rparity_xor;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__counter_b;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rf_push_q;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rf_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rcounter16_eq_7;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rcounter16_eq_0;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rcounter16_minus_1;
        CData/*7:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__data8_out;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__top;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__bottom;
        CData/*3:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__top_plus_1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__rfifo__DOT__we;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__m_wready;
        CData/*1:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_arburst;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_arid;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_arlen;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_arlen_last;
        CData/*2:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_arsize;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_queue_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_queue_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_queue_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_valid;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_rcur;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_rid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_rlast;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_rvalid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_awburst;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_awid;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_awlen;
        CData/*2:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_awsize;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_queue_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_queue_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_queue_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_allow_out;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_data;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_pop;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_queue_datas;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_queue_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_queue_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_queue_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_b_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_en;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_go;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_wlast;
        CData/*3:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_wstrb;
        CData/*0:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_wvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__m_wready;
        CData/*1:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_arburst;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_arid;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_arlen;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_arlen_last;
        CData/*2:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_arsize;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_queue_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_queue_push;
    };
    struct {
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_queue_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_en;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_rcur;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_rid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_rlast;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_rvalid;
        CData/*1:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_awburst;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_awid;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_awlen;
        CData/*2:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_awsize;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_queue_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_queue_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_queue_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_allow_out;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_data;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_pop;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_queue_datas;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_queue_pop;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_queue_push;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_queue_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_b_valid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_en;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_go;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_wlast;
        CData/*3:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_wstrb;
        CData/*0:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_wvalid;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__conf_ren;
        CData/*3:0*/ simu_top__DOT__soc__DOT__confreg__DOT__conf_wen;
        CData/*7:0*/ simu_top__DOT__soc__DOT__confreg__DOT__confreg_uart_data;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__confreg_uart_valid;
        CData/*7:0*/ simu_top__DOT__soc__DOT__confreg__DOT__virtual_uart_data;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__open_trace;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__num_monitor;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer_begin;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer_begin_r1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer_begin_r2;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer_begin_r3;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer_end_r1;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer_end_r2;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_timer;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__write_uart_valid;
        CData/*2:0*/ simu_top__DOT__soc__DOT__confreg__DOT__state;
        CData/*2:0*/ simu_top__DOT__soc__DOT__confreg__DOT__next_state;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__key_flag;
        CData/*3:0*/ simu_top__DOT__soc__DOT__confreg__DOT__state_count;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__btn_step0_r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__btn_step1_r;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__step0_flag;
        CData/*0:0*/ simu_top__DOT__soc__DOT__confreg__DOT__step1_flag;
        CData/*3:0*/ simu_top__DOT__soc__DOT__confreg__DOT__scan_data;
        CData/*4:0*/ NAND_top__DOT__NAND_STATE;
        CData/*0:0*/ NAND_top__DOT__nand_clr_ack;
        CData/*0:0*/ NAND_top__DOT__NAND_DONE;
        CData/*0:0*/ NAND_top__DOT__NAND_CE_;
        CData/*0:0*/ NAND_top__DOT__NANDtag;
        CData/*0:0*/ NAND_top__DOT__NAND_IORDY;
        CData/*0:0*/ NAND_top__DOT__HIT0;
        CData/*0:0*/ NAND_top__DOT__HIT1;
        CData/*0:0*/ NAND_top__DOT__HIT2;
    };
    struct {
        CData/*0:0*/ NAND_top__DOT__HIT3;
        CData/*0:0*/ NAND_top__DOT__HIT6;
        CData/*0:0*/ NAND_top__DOT__HIT7;
        CData/*0:0*/ NAND_top__DOT__HIT8;
        CData/*0:0*/ NAND_top__DOT__HIT9;
        CData/*0:0*/ NAND_top__DOT__HIT10;
        CData/*0:0*/ NAND_top__DOT__HIT11;
        CData/*0:0*/ NAND_top__DOT__NAND_HIT;
        CData/*0:0*/ NAND_top__DOT__NAND_DMA_REQ;
        CData/*0:0*/ NAND_top__DOT__nand_cmd_valid;
        CData/*7:0*/ NAND_top__DOT__status;
        CData/*1:0*/ NAND_top__DOT__nand_number;
        CData/*0:0*/ NAND_top__DOT__NAND_CE_pre_o__BRA__3__KET__;
        CData/*0:0*/ NAND_top__DOT__NAND_CE_pre_o__BRA__2__KET__;
        CData/*0:0*/ NAND_top__DOT__NAND_CE_pre_o__BRA__1__KET__;
        CData/*0:0*/ NAND_top__DOT__NAND_CE_pre_o__BRA__0__KET__;
        CData/*0:0*/ NAND_top__DOT__NAND_IORDY_post_i__BRA__3__KET__;
        CData/*0:0*/ NAND_top__DOT__NAND_IORDY_post_i__BRA__2__KET__;
        CData/*0:0*/ NAND_top__DOT__NAND_IORDY_post_i__BRA__1__KET__;
        CData/*1:0*/ NAND_top__DOT__ADDR_pointer;
        CData/*2:0*/ NAND_top__DOT__NAND_ADDR_COUNT;
        CData/*7:0*/ NAND_top__DOT__WAIT_NUM;
        CData/*7:0*/ NAND_top__DOT__HOLD_NUM;
        CData/*7:0*/ NAND_top__DOT__COMMAND;
        CData/*4:0*/ NAND_top__DOT__PRE_STATE;
        CData/*2:0*/ NAND_top__DOT__READ_ID_NUM;
        CData/*0:0*/ NAND_top__DOT__NAND_GO;
        CData/*0:0*/ NAND_top__DOT__NAND_ACK;
        CData/*0:0*/ NAND_top__DOT__DMA_OP_DONE;
        CData/*0:0*/ NAND_top__DOT__ERASE_SERIAL;
        CData/*0:0*/ NAND_top__DOT__now_up_half;
        CData/*0:0*/ NAND_top__DOT__now_oob;
        CData/*2:0*/ __Vfunc_simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__get_num__7__Vfuncout;
        CData/*2:0*/ __Vfunc_simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__get_num__7__valid;
        CData/*2:0*/ __Vfunc_simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__get_num__7__pre_num;
        CData/*2:0*/ __Vfunc_simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__get_num__8__Vfuncout;
        CData/*2:0*/ __Vfunc_simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__get_num__8__valid;
        CData/*2:0*/ __Vfunc_simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__get_num__8__pre_num;
        CData/*4:0*/ __Vtableidx2;
        CData/*1:0*/ __Vtableidx4;
        CData/*7:0*/ __Vtableidx5;
        CData/*7:0*/ __Vtableidx8;
        CData/*7:0*/ __Vtableidx12;
        CData/*3:0*/ __VdfgRegularize_h6e95ff9d_0_0;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__aclk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__pclk__0;
        VL_OUT16(led,15,0);
        VL_IN16(ADDR,10,0);
        SData/*15:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__dlc;
        SData/*9:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__counter_t;
        SData/*8:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__M_cnt;
        SData/*8:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__M_next;
        SData/*10:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__rf_data_in;
        SData/*9:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__toc_value;
        SData/*15:0*/ simu_top__DOT__soc__DOT__confreg__DOT__btn_key_r;
        SData/*15:0*/ simu_top__DOT__soc__DOT__confreg__DOT__btn_key_tmp;
        SData/*13:0*/ NAND_top__DOT__nand_addr_c;
        SData/*15:0*/ NAND_top__DOT__nand_timing;
        SData/*13:0*/ NAND_top__DOT__WRITE_MAX_COUNT;
        SData/*13:0*/ NAND_top__DOT__READ_MAX_COUNT;
        SData/*13:0*/ NAND_top__DOT__data_count;
        SData/*9:0*/ __Vtableidx3;
    };
    struct {
        SData/*8:0*/ __Vtableidx11;
        VL_IN(random_seed,22,0);
        VL_OUT(ram_raddr,31,0);
        VL_IN(ram_rdata,31,0);
        VL_OUT(ram_waddr,31,0);
        VL_OUT(ram_wdata,31,0);
        VL_OUT(debug0_wb_pc,31,0);
        VL_OUT(debug0_wb_rf_wdata,31,0);
        VL_OUT(num_data,31,0);
        VL_OUTW(uart_ctr_bus,127,0,4);
        VL_IN(DAT_I,31,0);
        VL_OUT(DAT_O,31,0);
        IData/*31:0*/ simu_top__DOT__soc__DOT__m0_rdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__io_in_icache_r_in_rdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__io_in_dcache_r_in_rdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__io_in_uncache1_r_in_rdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__io_in_uncache2_r_in_rdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__axi_crossbar__DOT__io_out_ar_out_araddr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__miss_addr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__dcache__DOT__miss_addr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache1__DOT__miss_addr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__cpu__DOT__uncache2__DOT__miss_addr;
        IData/*22:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_random;
        IData/*22:0*/ simu_top__DOT__soc__DOT__delay__DOT__mask_random_next;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s1_rdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s4_rdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__w_addr_dir_int;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_addr_hit_int;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_addr_dir_int;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_fifo__DOT__i;
        IData/*31:0*/ simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_fifo__DOT__i;
        IData/*19:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_addr_dma;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_wdata_dma;
        IData/*23:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_high_24b_wr;
        IData/*19:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_uart0_addr;
        IData/*19:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_nand_addr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_nand_datai;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__apb_nand_datao;
        IData/*19:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__axi_s_req_addr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__reg_datai_32;
        IData/*31:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__AA_axi2apb_bridge_cpu__DOT__reg_datao_32;
        IData/*23:0*/ simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__dl;
        IData/*31:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_araddr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_data_araddr_next;
        IData/*31:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_awaddr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_data_awaddr_next;
        IData/*31:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_wdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_araddr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_data_araddr_next;
        IData/*31:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_awaddr;
        IData/*31:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_data_awaddr_next;
        IData/*31:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_wdata;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr0;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr1;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr2;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr3;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr4;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr5;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr6;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__cr7;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__led_data;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__led_rg0_data;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__led_rg1_data;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__num_data;
    };
    struct {
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__sw_inter_data;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__timer_r2;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__simu_flag;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__io_simu;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__conf_rdata_reg;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__conf_wdata_r;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__conf_wdata_r1;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__conf_wdata_r2;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__timer_r1;
        IData/*31:0*/ simu_top__DOT__soc__DOT__confreg__DOT__timer;
        IData/*19:0*/ simu_top__DOT__soc__DOT__confreg__DOT__key_count;
        IData/*19:0*/ simu_top__DOT__soc__DOT__confreg__DOT__step0_count;
        IData/*19:0*/ simu_top__DOT__soc__DOT__confreg__DOT__step1_count;
        IData/*19:0*/ simu_top__DOT__soc__DOT__confreg__DOT__count;
        IData/*31:0*/ NAND_top__DOT__REG_DAT_T;
        IData/*24:0*/ NAND_top__DOT__nand_addr_r;
        IData/*31:0*/ NAND_top__DOT__nand_op_num;
        IData/*31:0*/ NAND_top__DOT__nand_parameter;
        IData/*31:0*/ NAND_top__DOT__nand_ce_map0;
        IData/*31:0*/ NAND_top__DOT__nand_ce_map1;
        IData/*31:0*/ NAND_top__DOT__nand_rdy_map0;
        IData/*31:0*/ NAND_top__DOT__nand_rdy_map1;
        IData/*31:0*/ NAND_top__DOT__nand_command;
        IData/*31:0*/ NAND_top__DOT__NAND_OP_NUM;
        IData/*31:0*/ NAND_top__DOT__NAND_DAT_O_RD;
        IData/*31:0*/ NAND_top__DOT__NAND_DAT_I_WR;
        IData/*31:0*/ __VactIterCount;
        QData/*63:0*/ simu_top__DOT__soc__DOT__cpu__DOT__difftest__DOT__cycleCnt;
        QData/*63:0*/ simu_top__DOT__soc__DOT__cpu__DOT__difftest__DOT__instrCnt;
        QData/*63:0*/ simu_top__DOT__soc__DOT__cpu__DOT__difftest__DOT___cycleCnt_T_1;
        QData/*63:0*/ simu_top__DOT__soc__DOT__cpu__DOT__difftest__DOT___instrCnt_T_1;
        QData/*44:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_push_data;
        QData/*44:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_r_a_queue_datas;
        QData/*44:0*/ simu_top__DOT__soc__DOT__conf_axi_ram__DOT__ram_w_a_queue_datas;
        QData/*44:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_r_a_queue_datas;
        QData/*44:0*/ simu_top__DOT__soc__DOT__sram_axi_ram__DOT__ram_w_a_queue_datas;
        QData/*37:0*/ NAND_top__DOT__addr_in_die;
        QData/*47:0*/ NAND_top__DOT__ID_INFORM;
        QData/*37:0*/ NAND_top__DOT__NAND_ADDR;
        VlUnpacked<IData/*21:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__cache_tag;
        VlUnpacked<CData/*0:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__cache_valid;
        VlUnpacked<IData/*31:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__icache__DOT__cache_data;
        VlUnpacked<IData/*21:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__dcache__DOT__cache_tag;
        VlUnpacked<CData/*0:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__dcache__DOT__cache_valid;
        VlUnpacked<IData/*31:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__dcache__DOT__cache_data;
        VlUnpacked<IData/*21:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__uncache1__DOT__cache_tag;
        VlUnpacked<CData/*0:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__uncache1__DOT__cache_valid;
        VlUnpacked<IData/*31:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__uncache1__DOT__cache_data;
        VlUnpacked<IData/*21:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__uncache2__DOT__cache_tag;
        VlUnpacked<CData/*0:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__uncache2__DOT__cache_valid;
        VlUnpacked<IData/*31:0*/, 256> simu_top__DOT__soc__DOT__cpu__DOT__uncache2__DOT__cache_data;
        VlUnpacked<CData/*3:0*/, 5> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_bid;
        VlUnpacked<CData/*1:0*/, 5> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_bresp;
        VlUnpacked<CData/*3:0*/, 5> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_rid;
        VlUnpacked<IData/*31:0*/, 5> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_rdata;
        VlUnpacked<CData/*1:0*/, 5> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__s_rresp;
        VlUnpacked<CData/*4:0*/, 5> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__BASE_ADDR;
        VlUnpacked<CData/*2:0*/, 2> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__wr_fifo__DOT__fifo_ram;
        VlUnpacked<CData/*2:0*/, 2> simu_top__DOT__soc__DOT__AXI_SLAVE_MUX__DOT__rd_fifo__DOT__fifo_ram;
        VlUnpacked<CData/*7:0*/, 16> simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__transmitter__DOT__fifo_tx__DOT__tfifo__DOT__ram;
        VlUnpacked<CData/*2:0*/, 16> simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__fifo;
        VlUnpacked<CData/*7:0*/, 16> simu_top__DOT__soc__DOT__APB_DEV__DOT__uart0__DOT__regs__DOT__receiver__DOT__fifo_rx__DOT__rfifo__DOT__ram;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
    };
    struct {
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
        VlUnpacked<CData/*0:0*/, 4> __Vm_traceActivity;
    };

    // INTERNAL VARIABLES
    Vsimu_top__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vsimu_top___024root(Vsimu_top__Syms* symsp, const char* namep);
    ~Vsimu_top___024root();
    VL_UNCOPYABLE(Vsimu_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
    void __Vserialize(VerilatedSerialize& os);
    void __Vdeserialize(VerilatedDeserialize& os);
};


#endif  // guard
