package nscscc

import chisel3._
import chisel3.util._
import config._
import java.io.File
import java.nio.charset.StandardCharsets
import java.nio.file.{Files, Path}
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter
import scala.sys.process._

// ================================================================
// 统一 Verilog 生成入口
// ================================================================
object CoreGen extends App {

  // 提取公共删除函数
  def cleanAndMkdir(dirPath: String): File = {
    val dir = new File(dirPath)
    if (dir.exists() && dir.isDirectory) {
      def deleteRecursively(f: File): Unit = {
        if (f.isDirectory) f.listFiles().foreach(deleteRecursively)
        if (f.exists && !f.delete())
          throw new Exception(s"Exception DeleFail: ${f.getAbsolutePath}")
      }
      deleteRecursively(dir)
    }
    dir.mkdirs()
    dir
  }

  def tryRun(cmd: Seq[String], cwd: File): Option[String] = {
    try {
      val out = Process(cmd, cwd).!!.trim
      if (out.nonEmpty) Some(out) else None
    } catch {
      case _: Throwable => None
    }
  }

  def prependHeaderComment(file: Path, header: String): Unit = {
    val oldContent = Files.readString(file, StandardCharsets.UTF_8)
    Files.writeString(file, header + oldContent, StandardCharsets.UTF_8)
  }

  // 读取第一个参数，默认 simu
  val mode = args.headOption.getOrElse("simu").toLowerCase match {
    case "fpga" => "fpga"
    case _      => "simu"
  }

  val targetDirPath = mode match {
    case "simu" => "./../chiplab/IP/myCPU/Chisel"
    case "fpga" => "./../chiplab/IP/myCPU/FPGA"
  }

  val enableDifftest = mode == "simu"  // simu 开启 difftest，fpga 关闭

  val targetDir = cleanAndMkdir(targetDirPath)
  val repoRoot = new File(".").getCanonicalFile

  implicit val config: Parameters = new Parameters(Map(
    DebugConfigKeys.EnableDifftest -> enableDifftest
  ))

  emitVerilog(
    new core_top,
    Array(
      "--target-dir", targetDirPath,
      "--emit-modules", "verilog"
    )
  )

  // 清理多余文件
  val filesToDelete = List("core_top.anno.json", "core_top.fir")
  filesToDelete.foreach { filename =>
    val fileToDelete = new File(targetDirPath, filename)
    if (fileToDelete.exists()) fileToDelete.delete()
  }

  val generatedAt = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))
  val gitCommit = tryRun(Seq("git", "rev-parse", "--short", "HEAD"), repoRoot).getOrElse("unknown")
  val gitBranch = tryRun(Seq("git", "rev-parse", "--abbrev-ref", "HEAD"), repoRoot).getOrElse("unknown")
  val gitCommitSubject = tryRun(Seq("git", "log", "-1", "--pretty=%s", "HEAD"), repoRoot).getOrElse("unknown")

  val header =
    s"""// ================================================================
       |// Auto-generated by CoreGen
       |// Generated at    : $generatedAt
       |// Mode            : $mode
       |// Git branch      : $gitBranch
       |// Git commit      : $gitCommit
       |// Git message     : $gitCommitSubject
       |// ---------------------------------------------------------------
       |// BPU  : useBPUV0=${config(CoreConfigKeys.UseBPUV0)}, btbSize=${config(CoreConfigKeys.BtbSize)}, phtSize=${config(CoreConfigKeys.PhtSize)}
       |// Cache: nSets=${config(CoreConfigKeys.NSets)}, nWays=${config(CoreConfigKeys.NWays)}, nMshrEntries=${config(CoreConfigKeys.NMshrEntries)}
       |// Pipe : ibufDepth=${config(CoreConfigKeys.IbufDepth)}, RobSize=${config(CoreConfigKeys.RobSize)}, SnapshotNum=${config(CoreConfigKeys.SnapshotNum)}
       |//        CommitWidth=${config(CoreConfigKeys.CommitWidth)}, LqSize=${config(CoreConfigKeys.LqSize)}, SqSize=${config(CoreConfigKeys.SqSize)}
       |// IQ   : IQ1=${config(CoreConfigKeys.IQ1Params).numEntries}, IQ2=${config(CoreConfigKeys.IQ2Params).numEntries}, IQ3=${config(CoreConfigKeys.IQ3Params).numEntries}
       |//        IQ4=${config(CoreConfigKeys.IQ4Params).numEntries}, IQ5=${config(CoreConfigKeys.IQ5Params).numEntries}
       |// ================================================================
       |
       |""".stripMargin

  val verilogFiles = Option(targetDir.listFiles()).getOrElse(Array.empty)
    .filter(file => file.isFile && file.getName.endsWith(".v"))

  verilogFiles.foreach { file =>
    prependHeaderComment(file.toPath, header)
  }

  println(s"[CoreGen] Generated $mode version in $targetDirPath")
}
