module AXI3Crossbar4to1(
  input  [3:0]  io_in_icache_ar_out_arid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [31:0] io_in_icache_ar_out_araddr, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [7:0]  io_in_icache_ar_out_arlen, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [2:0]  io_in_icache_ar_out_arsize, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [1:0]  io_in_icache_ar_out_arburst, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [1:0]  io_in_icache_ar_out_arlock, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_icache_ar_out_arcache, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [2:0]  io_in_icache_ar_out_arprot, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_icache_ar_out_arvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_icache_ar_arready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_icache_aw_out_awid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [31:0] io_in_icache_aw_out_awaddr, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [7:0]  io_in_icache_aw_out_awlen, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [2:0]  io_in_icache_aw_out_awsize, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [1:0]  io_in_icache_aw_out_awburst, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [1:0]  io_in_icache_aw_out_awlock, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_icache_aw_out_awcache, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [2:0]  io_in_icache_aw_out_awprot, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_icache_aw_out_awvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_icache_aw_awready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_icache_w_out_wid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [31:0] io_in_icache_w_out_wdata, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_icache_w_out_wstrb, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_icache_w_out_wlast, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_icache_w_out_wvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_icache_w_wready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [3:0]  io_in_icache_r_in_rid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [31:0] io_in_icache_r_in_rdata, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [1:0]  io_in_icache_r_in_rresp, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_icache_r_in_rlast, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_icache_r_in_rvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_icache_r_rready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [3:0]  io_in_icache_b_in_bid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [1:0]  io_in_icache_b_in_bresp, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_icache_b_in_bvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_icache_b_bready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_dcache_ar_out_arid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [31:0] io_in_dcache_ar_out_araddr, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [7:0]  io_in_dcache_ar_out_arlen, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [2:0]  io_in_dcache_ar_out_arsize, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [1:0]  io_in_dcache_ar_out_arburst, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [1:0]  io_in_dcache_ar_out_arlock, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_dcache_ar_out_arcache, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [2:0]  io_in_dcache_ar_out_arprot, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_dcache_ar_out_arvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_dcache_ar_arready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_dcache_aw_out_awid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [31:0] io_in_dcache_aw_out_awaddr, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [7:0]  io_in_dcache_aw_out_awlen, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [2:0]  io_in_dcache_aw_out_awsize, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [1:0]  io_in_dcache_aw_out_awburst, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [1:0]  io_in_dcache_aw_out_awlock, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_dcache_aw_out_awcache, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [2:0]  io_in_dcache_aw_out_awprot, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_dcache_aw_out_awvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_dcache_aw_awready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_dcache_w_out_wid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [31:0] io_in_dcache_w_out_wdata, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_dcache_w_out_wstrb, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_dcache_w_out_wlast, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_dcache_w_out_wvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_dcache_w_wready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [3:0]  io_in_dcache_r_in_rid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [31:0] io_in_dcache_r_in_rdata, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [1:0]  io_in_dcache_r_in_rresp, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_dcache_r_in_rlast, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_dcache_r_in_rvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_dcache_r_rready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [3:0]  io_in_dcache_b_in_bid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [1:0]  io_in_dcache_b_in_bresp, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_dcache_b_in_bvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_dcache_b_bready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_uncache1_ar_out_arid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [31:0] io_in_uncache1_ar_out_araddr, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [7:0]  io_in_uncache1_ar_out_arlen, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [2:0]  io_in_uncache1_ar_out_arsize, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [1:0]  io_in_uncache1_ar_out_arburst, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [1:0]  io_in_uncache1_ar_out_arlock, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_uncache1_ar_out_arcache, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [2:0]  io_in_uncache1_ar_out_arprot, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_uncache1_ar_out_arvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_uncache1_ar_arready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_uncache1_aw_out_awid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [31:0] io_in_uncache1_aw_out_awaddr, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [7:0]  io_in_uncache1_aw_out_awlen, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [2:0]  io_in_uncache1_aw_out_awsize, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [1:0]  io_in_uncache1_aw_out_awburst, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [1:0]  io_in_uncache1_aw_out_awlock, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_uncache1_aw_out_awcache, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [2:0]  io_in_uncache1_aw_out_awprot, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_uncache1_aw_out_awvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_uncache1_aw_awready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_uncache1_w_out_wid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [31:0] io_in_uncache1_w_out_wdata, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_uncache1_w_out_wstrb, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_uncache1_w_out_wlast, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_uncache1_w_out_wvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_uncache1_w_wready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [3:0]  io_in_uncache1_r_in_rid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [31:0] io_in_uncache1_r_in_rdata, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [1:0]  io_in_uncache1_r_in_rresp, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_uncache1_r_in_rlast, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_uncache1_r_in_rvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_uncache1_r_rready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [3:0]  io_in_uncache1_b_in_bid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [1:0]  io_in_uncache1_b_in_bresp, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_uncache1_b_in_bvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_uncache1_b_bready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_uncache2_ar_out_arid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [31:0] io_in_uncache2_ar_out_araddr, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [7:0]  io_in_uncache2_ar_out_arlen, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [2:0]  io_in_uncache2_ar_out_arsize, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [1:0]  io_in_uncache2_ar_out_arburst, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [1:0]  io_in_uncache2_ar_out_arlock, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_uncache2_ar_out_arcache, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [2:0]  io_in_uncache2_ar_out_arprot, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_uncache2_ar_out_arvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_uncache2_ar_arready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_uncache2_aw_out_awid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [31:0] io_in_uncache2_aw_out_awaddr, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [7:0]  io_in_uncache2_aw_out_awlen, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [2:0]  io_in_uncache2_aw_out_awsize, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [1:0]  io_in_uncache2_aw_out_awburst, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [1:0]  io_in_uncache2_aw_out_awlock, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_uncache2_aw_out_awcache, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [2:0]  io_in_uncache2_aw_out_awprot, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_uncache2_aw_out_awvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_uncache2_aw_awready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_uncache2_w_out_wid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [31:0] io_in_uncache2_w_out_wdata, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_in_uncache2_w_out_wstrb, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_uncache2_w_out_wlast, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_uncache2_w_out_wvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_uncache2_w_wready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [3:0]  io_in_uncache2_r_in_rid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [31:0] io_in_uncache2_r_in_rdata, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [1:0]  io_in_uncache2_r_in_rresp, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_uncache2_r_in_rlast, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_uncache2_r_in_rvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_uncache2_r_rready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [3:0]  io_in_uncache2_b_in_bid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [1:0]  io_in_uncache2_b_in_bresp, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_in_uncache2_b_in_bvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_in_uncache2_b_bready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [3:0]  io_out_ar_out_arid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [31:0] io_out_ar_out_araddr, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [7:0]  io_out_ar_out_arlen, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [2:0]  io_out_ar_out_arsize, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [1:0]  io_out_ar_out_arburst, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [1:0]  io_out_ar_out_arlock, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [3:0]  io_out_ar_out_arcache, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [2:0]  io_out_ar_out_arprot, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_out_ar_out_arvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_out_ar_arready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [3:0]  io_out_aw_out_awid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [31:0] io_out_aw_out_awaddr, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [7:0]  io_out_aw_out_awlen, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [2:0]  io_out_aw_out_awsize, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [1:0]  io_out_aw_out_awburst, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [1:0]  io_out_aw_out_awlock, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [3:0]  io_out_aw_out_awcache, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [2:0]  io_out_aw_out_awprot, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_out_aw_out_awvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_out_aw_awready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [3:0]  io_out_w_out_wid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [31:0] io_out_w_out_wdata, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output [3:0]  io_out_w_out_wstrb, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_out_w_out_wlast, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_out_w_out_wvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_out_w_wready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_out_r_in_rid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [31:0] io_out_r_in_rdata, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [1:0]  io_out_r_in_rresp, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_out_r_in_rlast, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_out_r_in_rvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_out_r_rready, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [3:0]  io_out_b_in_bid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input  [1:0]  io_out_b_in_bresp, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  input         io_out_b_in_bvalid, // @[src/main/scala/AXI3Crossbar.scala 9:14]
  output        io_out_b_bready // @[src/main/scala/AXI3Crossbar.scala 9:14]
);
  wire  req_valid_0 = io_in_icache_ar_out_arvalid | io_in_icache_aw_out_awvalid; // @[src/main/scala/AXI3Crossbar.scala 29:33]
  wire  req_valid_1 = io_in_dcache_ar_out_arvalid | io_in_dcache_aw_out_awvalid; // @[src/main/scala/AXI3Crossbar.scala 30:33]
  wire  req_valid_2 = io_in_uncache1_ar_out_arvalid | io_in_uncache1_aw_out_awvalid; // @[src/main/scala/AXI3Crossbar.scala 31:35]
  wire [1:0] _sel_idx_T = req_valid_2 ? 2'h2 : 2'h3; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [1:0] _sel_idx_T_1 = req_valid_1 ? 2'h1 : _sel_idx_T; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire [1:0] sel_idx = req_valid_0 ? 2'h0 : _sel_idx_T_1; // @[src/main/scala/chisel3/util/Mux.scala 50:70]
  wire  _ar_sel_data_T = 2'h1 == sel_idx; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire [3:0] _ar_sel_data_T_1_arid = 2'h1 == sel_idx ? io_in_dcache_ar_out_arid : io_in_icache_ar_out_arid; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire [31:0] _ar_sel_data_T_1_araddr = 2'h1 == sel_idx ? io_in_dcache_ar_out_araddr : io_in_icache_ar_out_araddr; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire [7:0] _ar_sel_data_T_1_arlen = 2'h1 == sel_idx ? io_in_dcache_ar_out_arlen : io_in_icache_ar_out_arlen; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire [2:0] _ar_sel_data_T_1_arsize = 2'h1 == sel_idx ? io_in_dcache_ar_out_arsize : io_in_icache_ar_out_arsize; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire [1:0] _ar_sel_data_T_1_arburst = 2'h1 == sel_idx ? io_in_dcache_ar_out_arburst : io_in_icache_ar_out_arburst; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire [1:0] _ar_sel_data_T_1_arlock = 2'h1 == sel_idx ? io_in_dcache_ar_out_arlock : io_in_icache_ar_out_arlock; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire [3:0] _ar_sel_data_T_1_arcache = 2'h1 == sel_idx ? io_in_dcache_ar_out_arcache : io_in_icache_ar_out_arcache; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire [2:0] _ar_sel_data_T_1_arprot = 2'h1 == sel_idx ? io_in_dcache_ar_out_arprot : io_in_icache_ar_out_arprot; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire  _ar_sel_data_T_1_arvalid = 2'h1 == sel_idx ? io_in_dcache_ar_out_arvalid : io_in_icache_ar_out_arvalid; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire  _ar_sel_data_T_2 = 2'h2 == sel_idx; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire [3:0] _ar_sel_data_T_3_arid = 2'h2 == sel_idx ? io_in_uncache1_ar_out_arid : _ar_sel_data_T_1_arid; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire [31:0] _ar_sel_data_T_3_araddr = 2'h2 == sel_idx ? io_in_uncache1_ar_out_araddr : _ar_sel_data_T_1_araddr; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire [7:0] _ar_sel_data_T_3_arlen = 2'h2 == sel_idx ? io_in_uncache1_ar_out_arlen : _ar_sel_data_T_1_arlen; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire [2:0] _ar_sel_data_T_3_arsize = 2'h2 == sel_idx ? io_in_uncache1_ar_out_arsize : _ar_sel_data_T_1_arsize; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire [1:0] _ar_sel_data_T_3_arburst = 2'h2 == sel_idx ? io_in_uncache1_ar_out_arburst : _ar_sel_data_T_1_arburst; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire [1:0] _ar_sel_data_T_3_arlock = 2'h2 == sel_idx ? io_in_uncache1_ar_out_arlock : _ar_sel_data_T_1_arlock; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire [3:0] _ar_sel_data_T_3_arcache = 2'h2 == sel_idx ? io_in_uncache1_ar_out_arcache : _ar_sel_data_T_1_arcache; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire [2:0] _ar_sel_data_T_3_arprot = 2'h2 == sel_idx ? io_in_uncache1_ar_out_arprot : _ar_sel_data_T_1_arprot; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire  _ar_sel_data_T_3_arvalid = 2'h2 == sel_idx ? io_in_uncache1_ar_out_arvalid : _ar_sel_data_T_1_arvalid; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire  _ar_sel_data_T_4 = 2'h3 == sel_idx; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  wire  _io_in_icache_ar_arready_T = sel_idx == 2'h0; // @[src/main/scala/AXI3Crossbar.scala 59:44]
  wire  _io_in_dcache_ar_arready_T = sel_idx == 2'h1; // @[src/main/scala/AXI3Crossbar.scala 60:44]
  wire  _io_in_uncache1_ar_arready_T = sel_idx == 2'h2; // @[src/main/scala/AXI3Crossbar.scala 61:44]
  wire  _io_in_uncache2_ar_arready_T = sel_idx == 2'h3; // @[src/main/scala/AXI3Crossbar.scala 62:44]
  wire [3:0] _aw_sel_data_T_1_awid = _ar_sel_data_T ? io_in_dcache_aw_out_awid : io_in_icache_aw_out_awid; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  wire [31:0] _aw_sel_data_T_1_awaddr = _ar_sel_data_T ? io_in_dcache_aw_out_awaddr : io_in_icache_aw_out_awaddr; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  wire [7:0] _aw_sel_data_T_1_awlen = _ar_sel_data_T ? io_in_dcache_aw_out_awlen : io_in_icache_aw_out_awlen; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  wire [2:0] _aw_sel_data_T_1_awsize = _ar_sel_data_T ? io_in_dcache_aw_out_awsize : io_in_icache_aw_out_awsize; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  wire [1:0] _aw_sel_data_T_1_awburst = _ar_sel_data_T ? io_in_dcache_aw_out_awburst : io_in_icache_aw_out_awburst; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  wire [1:0] _aw_sel_data_T_1_awlock = _ar_sel_data_T ? io_in_dcache_aw_out_awlock : io_in_icache_aw_out_awlock; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  wire [3:0] _aw_sel_data_T_1_awcache = _ar_sel_data_T ? io_in_dcache_aw_out_awcache : io_in_icache_aw_out_awcache; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  wire [2:0] _aw_sel_data_T_1_awprot = _ar_sel_data_T ? io_in_dcache_aw_out_awprot : io_in_icache_aw_out_awprot; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  wire  _aw_sel_data_T_1_awvalid = _ar_sel_data_T ? io_in_dcache_aw_out_awvalid : io_in_icache_aw_out_awvalid; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  wire [3:0] _aw_sel_data_T_3_awid = _ar_sel_data_T_2 ? io_in_uncache1_aw_out_awid : _aw_sel_data_T_1_awid; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  wire [31:0] _aw_sel_data_T_3_awaddr = _ar_sel_data_T_2 ? io_in_uncache1_aw_out_awaddr : _aw_sel_data_T_1_awaddr; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  wire [7:0] _aw_sel_data_T_3_awlen = _ar_sel_data_T_2 ? io_in_uncache1_aw_out_awlen : _aw_sel_data_T_1_awlen; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  wire [2:0] _aw_sel_data_T_3_awsize = _ar_sel_data_T_2 ? io_in_uncache1_aw_out_awsize : _aw_sel_data_T_1_awsize; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  wire [1:0] _aw_sel_data_T_3_awburst = _ar_sel_data_T_2 ? io_in_uncache1_aw_out_awburst : _aw_sel_data_T_1_awburst; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  wire [1:0] _aw_sel_data_T_3_awlock = _ar_sel_data_T_2 ? io_in_uncache1_aw_out_awlock : _aw_sel_data_T_1_awlock; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  wire [3:0] _aw_sel_data_T_3_awcache = _ar_sel_data_T_2 ? io_in_uncache1_aw_out_awcache : _aw_sel_data_T_1_awcache; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  wire [2:0] _aw_sel_data_T_3_awprot = _ar_sel_data_T_2 ? io_in_uncache1_aw_out_awprot : _aw_sel_data_T_1_awprot; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  wire  _aw_sel_data_T_3_awvalid = _ar_sel_data_T_2 ? io_in_uncache1_aw_out_awvalid : _aw_sel_data_T_1_awvalid; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  wire [3:0] _w_sel_data_T_1_wid = _ar_sel_data_T ? io_in_dcache_w_out_wid : io_in_icache_w_out_wid; // @[src/main/scala/AXI3Crossbar.scala 93:53]
  wire [31:0] _w_sel_data_T_1_wdata = _ar_sel_data_T ? io_in_dcache_w_out_wdata : io_in_icache_w_out_wdata; // @[src/main/scala/AXI3Crossbar.scala 93:53]
  wire [3:0] _w_sel_data_T_1_wstrb = _ar_sel_data_T ? io_in_dcache_w_out_wstrb : io_in_icache_w_out_wstrb; // @[src/main/scala/AXI3Crossbar.scala 93:53]
  wire  _w_sel_data_T_1_wlast = _ar_sel_data_T ? io_in_dcache_w_out_wlast : io_in_icache_w_out_wlast; // @[src/main/scala/AXI3Crossbar.scala 93:53]
  wire  _w_sel_data_T_1_wvalid = _ar_sel_data_T ? io_in_dcache_w_out_wvalid : io_in_icache_w_out_wvalid; // @[src/main/scala/AXI3Crossbar.scala 93:53]
  wire [3:0] _w_sel_data_T_3_wid = _ar_sel_data_T_2 ? io_in_uncache1_w_out_wid : _w_sel_data_T_1_wid; // @[src/main/scala/AXI3Crossbar.scala 93:53]
  wire [31:0] _w_sel_data_T_3_wdata = _ar_sel_data_T_2 ? io_in_uncache1_w_out_wdata : _w_sel_data_T_1_wdata; // @[src/main/scala/AXI3Crossbar.scala 93:53]
  wire [3:0] _w_sel_data_T_3_wstrb = _ar_sel_data_T_2 ? io_in_uncache1_w_out_wstrb : _w_sel_data_T_1_wstrb; // @[src/main/scala/AXI3Crossbar.scala 93:53]
  wire  _w_sel_data_T_3_wlast = _ar_sel_data_T_2 ? io_in_uncache1_w_out_wlast : _w_sel_data_T_1_wlast; // @[src/main/scala/AXI3Crossbar.scala 93:53]
  wire  _w_sel_data_T_3_wvalid = _ar_sel_data_T_2 ? io_in_uncache1_w_out_wvalid : _w_sel_data_T_1_wvalid; // @[src/main/scala/AXI3Crossbar.scala 93:53]
  wire  _io_out_r_rready_T_1 = _ar_sel_data_T ? io_in_dcache_r_rready : io_in_icache_r_rready; // @[src/main/scala/AXI3Crossbar.scala 110:63]
  wire  _io_out_r_rready_T_3 = _ar_sel_data_T_2 ? io_in_uncache1_r_rready : _io_out_r_rready_T_1; // @[src/main/scala/AXI3Crossbar.scala 110:63]
  wire  _io_out_b_bready_T_1 = _ar_sel_data_T ? io_in_dcache_b_bready : io_in_icache_b_bready; // @[src/main/scala/AXI3Crossbar.scala 127:63]
  wire  _io_out_b_bready_T_3 = _ar_sel_data_T_2 ? io_in_uncache1_b_bready : _io_out_b_bready_T_1; // @[src/main/scala/AXI3Crossbar.scala 127:63]
  assign io_in_icache_ar_arready = sel_idx == 2'h0 & io_out_ar_arready; // @[src/main/scala/AXI3Crossbar.scala 59:35]
  assign io_in_icache_aw_awready = _io_in_icache_ar_arready_T & io_out_aw_awready; // @[src/main/scala/AXI3Crossbar.scala 80:35]
  assign io_in_icache_w_wready = _io_in_icache_ar_arready_T & io_out_w_wready; // @[src/main/scala/AXI3Crossbar.scala 101:33]
  assign io_in_icache_r_in_rid = _io_in_icache_ar_arready_T ? io_out_r_in_rid : 4'h0; // @[src/main/scala/AXI3Crossbar.scala 118:27]
  assign io_in_icache_r_in_rdata = _io_in_icache_ar_arready_T ? io_out_r_in_rdata : 32'h0; // @[src/main/scala/AXI3Crossbar.scala 118:27]
  assign io_in_icache_r_in_rresp = _io_in_icache_ar_arready_T ? io_out_r_in_rresp : 2'h0; // @[src/main/scala/AXI3Crossbar.scala 118:27]
  assign io_in_icache_r_in_rlast = _io_in_icache_ar_arready_T & io_out_r_in_rlast; // @[src/main/scala/AXI3Crossbar.scala 118:27]
  assign io_in_icache_r_in_rvalid = _io_in_icache_ar_arready_T & io_out_r_in_rvalid; // @[src/main/scala/AXI3Crossbar.scala 118:27]
  assign io_in_icache_b_in_bid = _io_in_icache_ar_arready_T ? io_out_b_in_bid : 4'h0; // @[src/main/scala/AXI3Crossbar.scala 135:27]
  assign io_in_icache_b_in_bresp = _io_in_icache_ar_arready_T ? io_out_b_in_bresp : 2'h0; // @[src/main/scala/AXI3Crossbar.scala 135:27]
  assign io_in_icache_b_in_bvalid = _io_in_icache_ar_arready_T & io_out_b_in_bvalid; // @[src/main/scala/AXI3Crossbar.scala 135:27]
  assign io_in_dcache_ar_arready = sel_idx == 2'h1 & io_out_ar_arready; // @[src/main/scala/AXI3Crossbar.scala 60:35]
  assign io_in_dcache_aw_awready = _io_in_dcache_ar_arready_T & io_out_aw_awready; // @[src/main/scala/AXI3Crossbar.scala 81:35]
  assign io_in_dcache_w_wready = _io_in_dcache_ar_arready_T & io_out_w_wready; // @[src/main/scala/AXI3Crossbar.scala 102:33]
  assign io_in_dcache_r_in_rid = _io_in_dcache_ar_arready_T ? io_out_r_in_rid : 4'h0; // @[src/main/scala/AXI3Crossbar.scala 119:27]
  assign io_in_dcache_r_in_rdata = _io_in_dcache_ar_arready_T ? io_out_r_in_rdata : 32'h0; // @[src/main/scala/AXI3Crossbar.scala 119:27]
  assign io_in_dcache_r_in_rresp = _io_in_dcache_ar_arready_T ? io_out_r_in_rresp : 2'h0; // @[src/main/scala/AXI3Crossbar.scala 119:27]
  assign io_in_dcache_r_in_rlast = _io_in_dcache_ar_arready_T & io_out_r_in_rlast; // @[src/main/scala/AXI3Crossbar.scala 119:27]
  assign io_in_dcache_r_in_rvalid = _io_in_dcache_ar_arready_T & io_out_r_in_rvalid; // @[src/main/scala/AXI3Crossbar.scala 119:27]
  assign io_in_dcache_b_in_bid = _io_in_dcache_ar_arready_T ? io_out_b_in_bid : 4'h0; // @[src/main/scala/AXI3Crossbar.scala 136:27]
  assign io_in_dcache_b_in_bresp = _io_in_dcache_ar_arready_T ? io_out_b_in_bresp : 2'h0; // @[src/main/scala/AXI3Crossbar.scala 136:27]
  assign io_in_dcache_b_in_bvalid = _io_in_dcache_ar_arready_T & io_out_b_in_bvalid; // @[src/main/scala/AXI3Crossbar.scala 136:27]
  assign io_in_uncache1_ar_arready = sel_idx == 2'h2 & io_out_ar_arready; // @[src/main/scala/AXI3Crossbar.scala 61:35]
  assign io_in_uncache1_aw_awready = _io_in_uncache1_ar_arready_T & io_out_aw_awready; // @[src/main/scala/AXI3Crossbar.scala 82:35]
  assign io_in_uncache1_w_wready = _io_in_uncache1_ar_arready_T & io_out_w_wready; // @[src/main/scala/AXI3Crossbar.scala 103:33]
  assign io_in_uncache1_r_in_rid = _io_in_uncache1_ar_arready_T ? io_out_r_in_rid : 4'h0; // @[src/main/scala/AXI3Crossbar.scala 120:29]
  assign io_in_uncache1_r_in_rdata = _io_in_uncache1_ar_arready_T ? io_out_r_in_rdata : 32'h0; // @[src/main/scala/AXI3Crossbar.scala 120:29]
  assign io_in_uncache1_r_in_rresp = _io_in_uncache1_ar_arready_T ? io_out_r_in_rresp : 2'h0; // @[src/main/scala/AXI3Crossbar.scala 120:29]
  assign io_in_uncache1_r_in_rlast = _io_in_uncache1_ar_arready_T & io_out_r_in_rlast; // @[src/main/scala/AXI3Crossbar.scala 120:29]
  assign io_in_uncache1_r_in_rvalid = _io_in_uncache1_ar_arready_T & io_out_r_in_rvalid; // @[src/main/scala/AXI3Crossbar.scala 120:29]
  assign io_in_uncache1_b_in_bid = _io_in_uncache1_ar_arready_T ? io_out_b_in_bid : 4'h0; // @[src/main/scala/AXI3Crossbar.scala 137:29]
  assign io_in_uncache1_b_in_bresp = _io_in_uncache1_ar_arready_T ? io_out_b_in_bresp : 2'h0; // @[src/main/scala/AXI3Crossbar.scala 137:29]
  assign io_in_uncache1_b_in_bvalid = _io_in_uncache1_ar_arready_T & io_out_b_in_bvalid; // @[src/main/scala/AXI3Crossbar.scala 137:29]
  assign io_in_uncache2_ar_arready = sel_idx == 2'h3 & io_out_ar_arready; // @[src/main/scala/AXI3Crossbar.scala 62:35]
  assign io_in_uncache2_aw_awready = _io_in_uncache2_ar_arready_T & io_out_aw_awready; // @[src/main/scala/AXI3Crossbar.scala 83:35]
  assign io_in_uncache2_w_wready = _io_in_uncache2_ar_arready_T & io_out_w_wready; // @[src/main/scala/AXI3Crossbar.scala 104:33]
  assign io_in_uncache2_r_in_rid = _io_in_uncache2_ar_arready_T ? io_out_r_in_rid : 4'h0; // @[src/main/scala/AXI3Crossbar.scala 121:29]
  assign io_in_uncache2_r_in_rdata = _io_in_uncache2_ar_arready_T ? io_out_r_in_rdata : 32'h0; // @[src/main/scala/AXI3Crossbar.scala 121:29]
  assign io_in_uncache2_r_in_rresp = _io_in_uncache2_ar_arready_T ? io_out_r_in_rresp : 2'h0; // @[src/main/scala/AXI3Crossbar.scala 121:29]
  assign io_in_uncache2_r_in_rlast = _io_in_uncache2_ar_arready_T & io_out_r_in_rlast; // @[src/main/scala/AXI3Crossbar.scala 121:29]
  assign io_in_uncache2_r_in_rvalid = _io_in_uncache2_ar_arready_T & io_out_r_in_rvalid; // @[src/main/scala/AXI3Crossbar.scala 121:29]
  assign io_in_uncache2_b_in_bid = _io_in_uncache2_ar_arready_T ? io_out_b_in_bid : 4'h0; // @[src/main/scala/AXI3Crossbar.scala 138:29]
  assign io_in_uncache2_b_in_bresp = _io_in_uncache2_ar_arready_T ? io_out_b_in_bresp : 2'h0; // @[src/main/scala/AXI3Crossbar.scala 138:29]
  assign io_in_uncache2_b_in_bvalid = _io_in_uncache2_ar_arready_T & io_out_b_in_bvalid; // @[src/main/scala/AXI3Crossbar.scala 138:29]
  assign io_out_ar_out_arid = 2'h3 == sel_idx ? io_in_uncache2_ar_out_arid : _ar_sel_data_T_3_arid; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  assign io_out_ar_out_araddr = 2'h3 == sel_idx ? io_in_uncache2_ar_out_araddr : _ar_sel_data_T_3_araddr; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  assign io_out_ar_out_arlen = 2'h3 == sel_idx ? io_in_uncache2_ar_out_arlen : _ar_sel_data_T_3_arlen; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  assign io_out_ar_out_arsize = 2'h3 == sel_idx ? io_in_uncache2_ar_out_arsize : _ar_sel_data_T_3_arsize; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  assign io_out_ar_out_arburst = 2'h3 == sel_idx ? io_in_uncache2_ar_out_arburst : _ar_sel_data_T_3_arburst; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  assign io_out_ar_out_arlock = 2'h3 == sel_idx ? io_in_uncache2_ar_out_arlock : _ar_sel_data_T_3_arlock; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  assign io_out_ar_out_arcache = 2'h3 == sel_idx ? io_in_uncache2_ar_out_arcache : _ar_sel_data_T_3_arcache; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  assign io_out_ar_out_arprot = 2'h3 == sel_idx ? io_in_uncache2_ar_out_arprot : _ar_sel_data_T_3_arprot; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  assign io_out_ar_out_arvalid = 2'h3 == sel_idx ? io_in_uncache2_ar_out_arvalid : _ar_sel_data_T_3_arvalid; // @[src/main/scala/AXI3Crossbar.scala 49:55]
  assign io_out_aw_out_awid = _ar_sel_data_T_4 ? io_in_uncache2_aw_out_awid : _aw_sel_data_T_3_awid; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  assign io_out_aw_out_awaddr = _ar_sel_data_T_4 ? io_in_uncache2_aw_out_awaddr : _aw_sel_data_T_3_awaddr; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  assign io_out_aw_out_awlen = _ar_sel_data_T_4 ? io_in_uncache2_aw_out_awlen : _aw_sel_data_T_3_awlen; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  assign io_out_aw_out_awsize = _ar_sel_data_T_4 ? io_in_uncache2_aw_out_awsize : _aw_sel_data_T_3_awsize; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  assign io_out_aw_out_awburst = _ar_sel_data_T_4 ? io_in_uncache2_aw_out_awburst : _aw_sel_data_T_3_awburst; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  assign io_out_aw_out_awlock = _ar_sel_data_T_4 ? io_in_uncache2_aw_out_awlock : _aw_sel_data_T_3_awlock; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  assign io_out_aw_out_awcache = _ar_sel_data_T_4 ? io_in_uncache2_aw_out_awcache : _aw_sel_data_T_3_awcache; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  assign io_out_aw_out_awprot = _ar_sel_data_T_4 ? io_in_uncache2_aw_out_awprot : _aw_sel_data_T_3_awprot; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  assign io_out_aw_out_awvalid = _ar_sel_data_T_4 ? io_in_uncache2_aw_out_awvalid : _aw_sel_data_T_3_awvalid; // @[src/main/scala/AXI3Crossbar.scala 72:55]
  assign io_out_w_out_wid = _ar_sel_data_T_4 ? io_in_uncache2_w_out_wid : _w_sel_data_T_3_wid; // @[src/main/scala/AXI3Crossbar.scala 93:53]
  assign io_out_w_out_wdata = _ar_sel_data_T_4 ? io_in_uncache2_w_out_wdata : _w_sel_data_T_3_wdata; // @[src/main/scala/AXI3Crossbar.scala 93:53]
  assign io_out_w_out_wstrb = _ar_sel_data_T_4 ? io_in_uncache2_w_out_wstrb : _w_sel_data_T_3_wstrb; // @[src/main/scala/AXI3Crossbar.scala 93:53]
  assign io_out_w_out_wlast = _ar_sel_data_T_4 ? io_in_uncache2_w_out_wlast : _w_sel_data_T_3_wlast; // @[src/main/scala/AXI3Crossbar.scala 93:53]
  assign io_out_w_out_wvalid = _ar_sel_data_T_4 ? io_in_uncache2_w_out_wvalid : _w_sel_data_T_3_wvalid; // @[src/main/scala/AXI3Crossbar.scala 93:53]
  assign io_out_r_rready = _ar_sel_data_T_4 ? io_in_uncache2_r_rready : _io_out_r_rready_T_3; // @[src/main/scala/AXI3Crossbar.scala 110:63]
  assign io_out_b_bready = _ar_sel_data_T_4 ? io_in_uncache2_b_bready : _io_out_b_bready_T_3; // @[src/main/scala/AXI3Crossbar.scala 127:63]
endmodule
